### ISSUE TITLE
Can't restart the server

### ISSUE THREAD

**Issue by acmgit** [minetest-mapserver/mapserver_mod#32]
Jan 24 10:35:22 zeitsprung systemd[1]: Started Lifemap for a running Minetest-Server.
Jan 24 10:35:22 zeitsprung mapserver[145336]: panic: invalid character ']' looking for beginning of value
Jan 24 10:35:22 zeitsprung mapserver[145336]: goroutine 1 [running]:
Jan 24 10:35:22 zeitsprung mapserver[145336]: main.main()
Jan 24 10:35:22 zeitsprung mapserver[145336]:         /home/runner/work/mapserver/mapserver/main.go:53 +0x3ca
Jan 24 10:35:22 zeitsprung systemd[1]: minetest_mapserver.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 24 10:35:22 zeitsprung systemd[1]: minetest_mapserver.service: Failed with result 'exit-code'.

**Comment by BuckarooBanzay** [comment]
> panic: invalid character ']' looking for beginning of value

can you post the `mapserver.json` file here but without the `secretkey` value?

**Comment by acmgit** [comment]
of course

```
{
	"configversion": 1,
	"port": 8081,
	"enableprometheus": true,
	"enablerendering": true,
	"enablesearch": true,
	"enableinitialrendering": true,
	"enabletransparency": false,
	"enablemediarepository": false,
	"webdev": false,
	"webapi": {
		"enablemapblock": false,
		"secretkey": "xxxxxxxx"
	},
	"layers": [
		{
			"id": 0,
			"name": "Ground",
			"from": -10,
			"to": 100
		},

	],
	"renderingfetchlimit": 500,
	"renderingjobs": 6,
	"renderingqueue": 10,
	"incrementalrenderingtimer": "5s",
	"mapobjects": {
		"areas": true,
		"bones": true,
		"protector": false,
		"xpprotector": true,
		"privprotector": false,
		"technic_quarry": false,
		"technic_switch": false,
		"technic_anchor": false,
		"technic_reactor": false,
		"luacontroller": false,
		"digiterms": false,
		"digilines": false,
		"travelnet": true,
		"mapserver_player": true,
		"mapserver_poi": true,
		"mapserver_label": true,
		"mapserver_trainline": false,
		"mapserver_border": true,
		"tileserverlegacy": true,
		"mission": false,
		"jumpdrive": false,
		"smartshop": true,
		"fancyvend": false,
		"atm": false,
		"train": false,
		"trainsignal": false,
		"minecart": true,
		"locator": false,
		"signs": true,
		"mapserver_airutils": false
	},
	"mapblockaccessor": {
		"expiretime": "10s",
		"purgetime": "15s",
		"maxitems": 50
	},
	"defaultoverlays": [
		"mapserver_poi",
		"mapserver_label",
		"mapserver_player"
	],
	"skins": {
		"enableskinsdb": true,
		"skinspath": "/usr/share/minetest/games/Smalltech_Game/mods/skinsdb/textures"
	},
	"worldpath": "./",
	"datapath": "./",
	"ColorsTxtPath": "./"
}

```

**Comment by acmgit** [comment]
I found it:

It was the , at the end of the section layers. 

```
"layers": [
		{
			"id": 0,
			"name": "Ground",
			"from": -10,
			"to": 100
		},
```
I removed it and the server restarts again.

**Comment by BuckarooBanzay** [comment]
> I removed it and the server restarts again.

nice, was that your editing on the file or did the program modify it that way?

**Comment by acmgit** [comment]
Was my own fault, the program works fine.
