### ISSUE TITLE
Cannot create poi for mapserver

### ISSUE THREAD

**Issue by whoo** [minetest-mapserver/mapserver_mod#7]
Hi,
I don't know how to setup a POI... and display it in mapserver.
- do I need a special mods (extra) ?
(I tried with minetest_poi without success)

Regards,
Dominique

**Comment by BuckarooBanzay** [comment]
> Hi,
> I don't know how to setup a POI... and display it in mapserver.
> 
>     * do I need a special mods (extra) ?
>       (I tried with minetest_poi without success)
> 
> 
> Regards,
> Dominique

Hey, no idea what the `minetest_poi` mod does but the mapserver currently only supports POI's and labels from this mod:
https://github.com/minetest-mapserver/mapserver_mod

There is also a "bridge" that connects the mod to the mapserver and displays additional stats and player locations:
https://github.com/minetest-mapserver/mapserver/blob/master/doc/mod.md#active-mode

**Comment by whoo** [comment]
Thanks ...I found with your indications.
Just need to put a special node (POI; from inventory) + active-mode
---> mapserver:poi_blue

![dd](https://user-images.githubusercontent.com/1499543/81486437-c6cba680-9222-11ea-8aa2-d370478c1b1f.png)

--

**Comment by BuckarooBanzay** [comment]
>  Just need to put a special node (POI; from inventory) + active-mode

You don't need the active mode at all, its just for additional realtime stats, the POI's should work without it :)

**Comment by BuckarooBanzay** [comment]
closing this, thanks for reporting :+1:
