### ISSUE TITLE
Search teleport doesn't work

### ISSUE THREAD

**Issue by OgelGames** [minetest-mapserver/mapserver_mod#8]
I have the teleport privilege on pandorabox, but I can't get the teleport button to work. The formspec closes, but no message is shown, no sound is played, and I don't get teleported.

**Comment by BuckarooBanzay** [comment]
The "teleport" button triggers a search for air in a 3x3 flat area around the destination, (player pos +- 2 nodes):

https://github.com/minetest-mapserver/mapserver_mod/blob/52b5c97f305d50936367a3b4eb35a404541e3d99/bridge/search.lua#L41-L55

I noticed the failures to teleport too and bumped the limit from originally 1 node around the player (https://github.com/minetest-mapserver/mapserver_mod/commit/ae12aa35a8b2725b9139bd2af940c2d125320e0d)

Do you know how the target area looks like?
Bumping that to a higher value could solve the problem again, maybe 5 nodes?
With the side-effect that someone can end up on the other side of a wall or in vacuum/lava :wink:

**Comment by OgelGames** [comment]
Did some testing and realized what the problem was: the code doesn't load the nodes around the target, so of course there's no air there... 😄 I think adding this on line 49 will fix it:
```lua
minetest.get_voxel_manip():read_from_map(pos1, pos2)
```
Also maybe for bones would it be better to teleport the player above them, in case they are in the air?

**Comment by BuckarooBanzay** [comment]
> the code doesn't load the nodes around the target

ugh, right :+1:

> Also maybe for bones would it be better to teleport the player above them, in case they are in the air?

good idea, it prevents further death traps if the bones are high up in the air :smile:
